name: Merge and Update Index

on:
  push:
    branches:
      - '*'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge branch
        run: |
          git checkout main
          git merge ${{ github.ref }}

      - name: Update index.html
        run: |
          sed -i "/<\/body>/i <a href='${{ github.ref }}/mygame/main.html'>${{ github.ref }}</a>" index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "cpdsWorkshop"
          git config --global user.email "clicpds@protonmail.com"
          git add index.html
          git commit -m "Update index.html"
          git push origin main
